# Generated by Django 3.1.7 on 2022-03-31 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photologue', '0011_auto_20190223_2138'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Savat', 'verbose_name_plural': 'Savatlar'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Korzinkadagi tovar', 'verbose_name_plural': 'Korzinkadagi tovarlar'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Zakaz', 'verbose_name_plural': 'Zakazlar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Tovar', 'verbose_name_plural': 'Tovarlar'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Zakaz qabul qilindo'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Foydalanuvchi sessiyasi'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='shop.cart', verbose_name='Savat'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price_sum',
            field=models.PositiveIntegerField(default=0, verbose_name='Jami'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Tavar'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='order',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Zakaz bajarildi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart', verbose_name='Savat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Borligiyokiyogligi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.gallery', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.photo', verbose_name='Rasm nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Nomi'),
        ),
    ]
